name: soan
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+2

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.0
  change_app_package_name: ^1.1.0
  country_code_picker: ^2.0.2
  dio: ^4.0.6
  dropdown_button2: ^1.9.2
  easy_localization: ^3.0.1
  flutter:
    sdk: flutter
  flutter_countdown_timer: ^4.1.0
  flutter_inappwebview: ^5.7.2+2
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: ^1.2.5
  flutter_phoenix: ^1.1.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.6.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.1.6
  flutter_test:
    sdk: flutter
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.2.2
  image_picker: ^0.8.6
  internet_connection_checker: ^1.0.0+1
  intl: ^0.17.0
  intl_phone_field: ^3.1.0
  jwt_decoder: ^2.0.1
  location: ^4.4.0
  modal_bottom_sheet: ^2.1.2
  open_file: ^3.2.1
  path_provider: ^2.0.11
  pdf: ^3.8.4
  percent_indicator: ^4.2.2
  pin_code_fields: ^7.4.0
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.7
  in_app_review: ^2.0.6

cupertino_icons: ^1.0.5

dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet

dev_dependencies:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/soan_launcher.png"
  adaptive_icon_background: "#0F4C81"
  adaptive_icon_foreground: "assets/icons/soan_launcher.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/translations/

fonts:
    - family: arial
      fonts:
        - asset: assets/arial.ttf
